### ISSUE TITLE
Timezone issues

### ISSUE THREAD

**Issue by XYZ69696** [tachiyomiorg/issue-moderator-action#632] opened 2024-01-09 23:52 UTC
I was updating my files today, January 10, 2024. However, I was shocked that the updates from yesterday were continued within the same date. Previously, whenever I update library entries on the next day, a new date appears on top of the updates. 

![Screenshot_20240110-073426](https://github.com/tachiyomiorg/issue-moderator-action/assets/155867662/1ff5fbf2-7512-4816-9459-2c8df7702871)

![Screenshot_20240110-073415](https://github.com/tachiyomiorg/issue-moderator-action/assets/155867662/8f9d855d-80a0-43d5-a5aa-3ca8ae32b354)

**Comment by arkon** [comment] 2024-01-10 03:14
Duplicate of https://github.com/tachiyomiorg/tachiyomi/issues/10381

**Closed by arkon** 2024-01-10 03:14 UTC
